name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Format
        run: |
	  cargo fmt --check
      - name: Build
        run: |
          cargo build --profile release
      - name: Run all tests
        run: |
          cargo test --all-features --profile release
